name: build Release
on: [push, pull_request]

jobs:
  build:
    name: build Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install third party libraries
        run: ./InstallThirdPartyLibraries.ps1

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild /m CppCoverage.sln /t:OpenCppCoverage  /p:Configuration=Release /p:Platform=x64

      - name: show list under build path
        run: dir .\x64\Release
